site_name: CodeSandbox
repo_url: https://github.com/fcarli/CodeSandbox
site_url: https://fcarli.github.io/CodeSandbox
site_description: This project aims at defining a fast, snappy and practical python sandbox that can be used with LLMs
site_author: Francesco Carli
edit_uri: edit/main/docs/
repo_name: fcarli/CodeSandbox
copyright: Maintained by <a href="https://fcarli.com">fcarli</a>.

nav:
  - Home: index.md
  - PythonSandboxManager Features: pythonsandboxmanager-features.md
  - Docker Setup: docker-setup.md
  - API Reference: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fcarli/CodeSandbox
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/CodeSandbox

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
