[project]
name = "CodeSandbox"
version = "0.1.0"
description = "Toml used to describe the environment used by the sandbox"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.6",
    "pandas>=2.2.3"]