"""
BioCage: A secure Python sandbox for LLM-generated code execution.

This package provides a safe, isolated environment for executing Python code
generated by Large Language Models (LLMs). It uses Docker containerization
to ensure security and prevent system contamination.

Key Features:
- Secure code execution in isolated containers
- JSON-formatted output with execution results
- Support for popular data science libraries
- Resource limits and timeout controls
- Multiple execution methods (stdin, environment variables)
"""

__version__ = "0.1.0"
__author__ = "Francesco Carli"
__email__ = "francesco.carli94@gmail.com"

try:
    from .biocage_manager import BioCageManager, SandboxExecutionResult

    __all__ = ["BioCageManager", "SandboxExecutionResult"]
except ImportError:
    # Handle import errors gracefully for documentation generation
    __all__ = []
